broadinstitute/Drop-seq

src/java/org/broadinstitute/dropseqrna/utils/editdistance/BarcodeSubstitutionCollection.java

This was a bug that was unlikely to surface in real data.

Fix confusion between array index and position in read.

---

build.xml
src/ant/defs.xml
src/java/org/broadinstitute/dropseqrna/annotation/ReduceGtf.java
src/java/org/broadinstitute/dropseqrna/barnyard/BarcodeListRetrieval.java
src/java/org/broadinstitute/dropseqrna/metrics/BamTagHistogram.java
src/java/org/broadinstitute/dropseqrna/metrics/BamTagOfTagCounts.java
src/java/org/broadinstitute/dropseqrna/utils/FilterBam.java
src/java/org/broadinstitute/dropseqrna/utils/FilterBamByTag.java
src/java/org/broadinstitute/dropseqrna/utils/editdistance/CollapseBarcodesInPlace.java
src/tests/java/org/broadinstitute/dropseqrna/annotation/ReduceGtfTest.java
src/tests/java/org/broadinstitute/dropseqrna/barnyard/DigitalExpressionTest.java
src/tests/java/org/broadinstitute/dropseqrna/barnyard/SingleCellRnaSeqMetricsCollectorTest.java
src/tests/java/org/broadinstitute/dropseqrna/metrics/BamTagHistogramTest.java
src/tests/java/org/broadinstitute/dropseqrna/metrics/BamTagOfTagCountsTest.java
src/tests/java/org/broadinstitute/dropseqrna/utils/FilterBamByTagTest.java
src/tests/java/org/broadinstitute/dropseqrna/utils/FilterBamTest.java

Eliminate obsoleted fully-qualified class name from ant macro.

Rationalize program names

---

src/ant/defs.xml

Pass TMPDIR enviroment variable to java.io.tmpdir for testng, if defined

---

src/java/org/broadinstitute/dropseqrna/annotation/GTFReader.java

(Otherwise GTFReader null pointers.  This is targeted at developers, not
users.)

GTFReader asserts that sequence dictionary isn't null

---

src/tests/java/org/broadinstitute/dropseqrna/barnyard/SingleCellRnaSeqMetricsCollectorTest.java

The new picard version mostly contains bug fixes.  See [Picard release notes](https://github.com/broadinstitute/picard/releasesl) for changes from 2.18.14 to 2.20.5.  One change that may be significant for some people is that count of RIBOSOMAL_BASES in SingleCellRnaSeqMetricsCollector can produce a slightly smaller number than previously.

Switch to picard release 2.20.5: changes count of RIBOSOMAL_BASES slightly

---

src/java/org/broadinstitute/dropseqrna/metrics/CountUnmatchedSampleIndices.java
src/tests/java/org/broadinstitute/dropseqrna/metrics/CountUnmatchedSampleIndicesTest.java

Don't allocate more threads than there are files.
Make a little more verbose.

Fail fast if no files found.

---

src/java/org/broadinstitute/dropseqrna/utils/readiterators/RequiredTagStringValuePredicate.java
src/tests/java/org/broadinstitute/dropseqrna/utils/TestUtils.java
src/tests/java/org/broadinstitute/dropseqrna/utils/readiterators/CellBarcodeFilteringIteratorTest.java

When set of required values was/null empty, operation was incorrect
Added unit tests to validate correct operation.

Fixed RequiredTagStringValuePredicate

---

src/java/org/broadinstitute/dropseqrna/barnyard/DGECommandLineBase.java
src/java/org/broadinstitute/dropseqrna/barnyard/DigitalExpression.java
src/java/org/broadinstitute/dropseqrna/barnyard/GatherMolecularBarcodeDistributionByGene.java

Removed INPUT from abstract class, so DGE can continue to have a single file input, and gatherMolBarcode can use multiple BAM inputs.

Removed INPUT from DGECommandLineBase

---

src/java/org/broadinstitute/dropseqrna/vcftools/SampleAssignmentVCFUtils.java

If all requested donors aren't in VCF, fail.

Make validateSampleNamesInVCF more stringent

---

src/java/org/broadinstitute/dropseqrna/censusseq/CensusSeq.java
src/java/org/broadinstitute/dropseqrna/censusseq/CommonSNPsData.java
src/java/org/broadinstitute/dropseqrna/censusseq/OptimizeGradientAdjustment.java
src/java/org/broadinstitute/dropseqrna/censusseq/OptimizeSampleRatiosCommonSNPs.java
src/java/org/broadinstitute/dropseqrna/censusseq/OptimizeSampleRatiosCommonSNPsResult.java
src/java/org/broadinstitute/dropseqrna/censusseq/OptimizeSampleRatiosGradientFunction.java
src/java/org/broadinstitute/dropseqrna/censusseq/OptimizeSampleRatiosLikelihoodFunctionCommonSNPs.java
src/tests/java/org/broadinstitute/dropseqrna/censusseq/CensusSeqTest.java
src/tests/java/org/broadinstitute/dropseqrna/censusseq/CommonSNPsDataTest.java
src/tests/java/org/broadinstitute/dropseqrna/censusseq/OptimizeSampleRatiosCommonSNPsTest.java
src/tests/java/org/broadinstitute/dropseqrna/censusseq/OptimizeSampleRatiosGradientFunctionTest.java

Update to CensusSeq:
Census now has an option (on by default) to scale the adjustment of donors at each iteration by the proportion of the donor from the last estimate.  This allows more smooth convergence of the mixture proportions and the ability to evaluate more difficult pools with many missing samples, at the cost of a slower convergence for more standard pools.  Likelihood of the data conditional on the donor mixture is equal or improved in all test cases.

Jn census update

---

src/java/org/broadinstitute/dropseqrna/barnyard/digitalexpression/FilterDge.java
src/java/org/broadinstitute/dropseqrna/eqtl/CreateMetaCells.java

When given an empty list of donors or cells to retain, these programs should produce a file containing the command summary header but no additional information.

FilterDge and CreateMetaCells handle empty cell / donor lists.

---

src/java/org/broadinstitute/dropseqrna/annotation/FunctionalDataProcessor.java
src/tests/java/org/broadinstitute/dropseqrna/utils/readiterators/FunctionalDataProcessorTest.java

This changes reads that had multiple annotations for the same gene: IE reads that overlap an intron/exon boundry.  This should not change the coding+intronic values we've been calculating for the last few years.
In integration tests this does not change any expression outputs.  
Added a few more unit tests to demonstrate parsing a difficult read annotation scenario multiple ways.

Fixed a bug in the way that gene annotations are simplified 

---

src/java/org/broadinstitute/dropseqrna/vcftools/filters/SimpleDiploidVariantContextFilter.java

See VCF spec for more details on symbolic alleles: https://samtools.github.io/hts-specs/VCFv4.3.pdf
These are complicated regions with (possibly) nested variants.  We don't need these for donor assignment or any method where we're directly observing simple alleles in sequence data.

Filter out sites with symbolic alleles when filtering to diploid sites

---

src/java/org/broadinstitute/dropseqrna/utils/AbstractSplitBamClp.java
src/java/org/broadinstitute/dropseqrna/utils/SplitBamByCell.java

SplitBamByCell defaults to not deleting input files.  Updated top line documentation with invokcation example

SplitBamByCell update

---

src/build/public_clp_template.sh

This fixes all errors reported by shellcheck and should therefore resolve issue #397 without the need to use `bash`. As I an unfamiliar with the build system, I have not actually confirmed that this fixes the issue but either way I think those changes are an improvement over the current code.

Fix shellcheck errors

---

src/scripts/Drop-seq_alignment.sh
src/scripts/create_Drop-seq_reference_metadata.sh
src/scripts/defs.sh

PR #398 addressed bash-isms and other errors reported by shellcheck for the Java wrapper scripts since those had a `#!/bin/sh` shebang line triggering error on systems using dash as `/bin/sh`.
Since `create_Drop-seq_reference_metadata.sh` and `Drop-seq_alignment.sh` have a `#!/usr/bin/env bash` shebang line and `defs.sh` is only sourced by those, they did not trigger any hard error and thus escaped my attention when when working on that commit. Nonetheless, those issues should be addressed as they might cause problems when running those scripts in an unusual environment (*e.g.* from/in a path containing spaces).
This PR fixes all shellcheck-reported issues with those scripts, while keeping the shebang lines unmodified (*i.e.* bash-isms in `create_Drop-seq_reference_metadata.sh` and …

Fix (more) shellcheck errors

---

src/scripts/Drop-seq_alignment.sh
src/scripts/create_Drop-seq_reference_metadata.sh

PR #401 addressed issues reported by shellcheck respecting the `#!/usr/bin/env bash` shebang.
This PR includes those changes but additionally removes all bash-isms from those scripts such that shellcheck passes with a plain `#!/bin/sh` shebang.
This increases portability by enabling to run those scripts on bash-less systems.
Previously used bash-features that had to be worked around are as follows:
1. `set -o pipefail`: Dropped, since neither script used a single pipe.
2. arrays (`files_to_delete`): Replaced by ~traps on exit without error.~ exploiting `$@` via `set --`.
---
~Notes:~
1. ~This has not been tested yet. I will report back once I have confirmed it does not break any functionality.  
Until the I'll leave this marked as a draft.~
2. ~This includes commit …

Drop bashisms

---

src/scripts/Drop-seq_alignment.sh

This adds an (optional) parameter `ncores` to the `Drop-seq_alignment.sh` script, to enable running STAR with more than just one thread.
This greatly improves the run-time of the script, if used.
The default value was chosen such that it matches STAR's default for the `--runThreadN` parameter. Thus, the bahaviour of the script remains identical when omitting the optional new parameter.

Alignment script: Add `ncores` parameter (for parallel STAR)

---

src/scripts/Drop-seq_alignment.sh

The log output of STAR can be very useful for sample QC and troubleshooting, plus it is very small.
Therefore, this PR moves it out of the temporary working directory along with the final BAM file and other log/stats files.

Alignment script: Preserve (final) STAR log

---

src/scripts/Drop-seq_alignment.sh

PR #412 mistakenly unset the `verbose` parameter after its (zero) initialization in `defs.sh` leading to downstream errors.
This PR fixes this. The comment already claimed to consider sourced files but now this is actually true.
---
@alecw: Apologies for letting this slip though.

Fix regression introduced by f235793

---

src/java/org/broadinstitute/dropseqrna/barnyard/digitalallelecounts/SNPUMIBasePileupIterator.java
src/tests/java/org/broadinstitute/dropseqrna/barnyard/digitalallelecounts/SNPUMIBasePileupIteratorTest.java

so reads without UMIs don't reach it.

Fix for #424: move STARSoloChimericReadFilteringIterator down

---

src/scripts/create_Drop-seq_reference_metadata.sh
src/scripts/defs.sh

- check for one and only one picard.jar is obsolete.
- if no -f arguments to create_Drop-seq_reference_metadata.sh, the filtered GTF had a trailing space

script bug fixes

---

src/java/org/broadinstitute/dropseqrna/barnyard/digitalallelecounts/LikelihoodUtils.java
src/java/org/broadinstitute/dropseqrna/barnyard/digitalallelecounts/SummarizeUMIBaseQualities.java

Fix for edge case bug where multiple reads are summarized as a single UMI with a single phred score.  Due to the underlying error rating being quantized by the pred score, a very high error rate of 0.9 or higher is quantized to a phred score of 0.  This is equivalent to an error rate of 1 when the phred score is unpacked to a probability, which causes errors with the downstream likelihoods.
To fix this, during summarization, if the phred score is less than 1 it is set to 1.  This avoids issues in the likelihood calculations where having probabilities of 0 causes issues when logged (plus probabilities should always include some uncertainty, which is lost if a phred score is 0.)

Fix for donor assignment negative infinity likelihoods.

---

src/java/org/broadinstitute/dropseqrna/utils/FilteredIterator.java
src/java/org/broadinstitute/dropseqrna/utils/PassFailTrackingIteratorI.java

In large datsets, 32 bit integers can be insufficient to counts the number of reads.
This PR replaces it by longs.
Reported by @jamesnemesh (https://github.com/broadinstitute/Drop-seq/issues/505).
Note:
A quick `git grep int\ record` did not reveal any additional hits. However, `git grep int\ read` reveals [a lot of places that might require conversion to long as well](https://github.com/search?q=repo%3Abroadinstitute%2FDrop-seq+%22int+read%22&type=code).
Therefore, I am creating this as a draft PR only for now to get a discussion started.
I think the quick search above contains quite some false positives, such as `readOneLength`, `readTwoLength`, `readMQ`, `readEditDistance`, `readQuality`, etc. that if at all should probably be changed into `short`s rather than `long`s.
However, things …

Convert record counts to long

---

.github/workflows/DropSeq.eqtl.r.yml
.github/workflows/python-dropseq_aggregation-conda.yml
.github/workflows/python-dropseq_hdf5-conda.yml
.github/workflows/python-dropseq_terra_utils-conda.yml

Potential fix for [https://github.com/broadinstitute/Drop-seq/security/code-scanning/7](https://github.com/broadinstitute/Drop-seq/security/code-scanning/7)
To fix the issue, we will add a `permissions` block at the root of the workflow file. This block will define the minimal permissions required for the workflow to function. Based on the provided workflow, it appears that the workflow primarily interacts with the repository contents and possibly pull requests. Therefore, we will set `contents: read` and add any additional permissions only if necessary.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 7: Workflow does not contain permissions

---

src/build/make_wrapper_scripts.sh
src/build/public_clp_template.sh
src/python/dropseq_hdf5/src/dropseq_hdf5/optimus_h5ad_to_dropseq.py

- Typo fix in optimus_h5ad_to_dropseq
- Explicitly use bash for java wrappers so that dash doesn't handle getopts' OPTIND differently

Updates for the Drop-seq pipeline:

---

src/R/packages/DropSeq.dropulation/R/DonorAssignmentStandardAnalysis.R

made plotFractionConfidentDoubletsFromSingleLikelihoodFit robust to having 0 doublets detected in the dataset.  Mostly annoying R stuff to pad dataframes appropriately.

plotFractionConfidentDoubletsFromSingleLikelihoodFit fix.
