- src/java/org/broadinstitute/dropseqrna/utils/CompareBAMTagValues.java
- src/java/org/broadinstitute/dropseqrna/utils/editdistance/CollapseBarcodesInPlace.java
- src/tests/java/org/broadinstitute/dropseqrna/utils/editdistance/CollapseBarcodesInPlaceTest.java
Added test BAMs from real data for substitutions and indels
Made new test utility class to compare tags on reads.
> Code coverage for CollapseBarcodesInPlace

- src/java/org/broadinstitute/dropseqrna/utils/editdistance/CollapseTagWithContext.java
- src/java/org/broadinstitute/dropseqrna/utils/editdistance/MapBarcodesByEditDistance.java
> Updates to some of the edit distance mapping tools to support new

- src/java/org/broadinstitute/dropseqrna/utils/editdistance/CollapseTagWithContext.java
Add mutational pathway collapse strategy
> Updates to CollapseTagWithContext 

- src/java/org/broadinstitute/dropseqrna/utils/CompareBAMTagValues.java
- src/java/org/broadinstitute/dropseqrna/utils/editdistance/CollapseTagWithContext.java
@alecw Can you do me a favor and look at the lowMemoryIteration method and tell me if that's just dumb or not?  Happy to walk you through it when you have time.
> CollapseTagWithContext memory optimizations.

- src/java/org/broadinstitute/dropseqrna/utils/CollectionSink.java
- src/java/org/broadinstitute/dropseqrna/utils/FilteredIterator.java
- src/java/org/broadinstitute/dropseqrna/utils/ObjectSink.java
- src/java/org/broadinstitute/dropseqrna/utils/PredicateFilteredIterator.java
- src/java/org/broadinstitute/dropseqrna/utils/SamWriterSink.java
- src/java/org/broadinstitute/dropseqrna/utils/SortingCollectionSink.java
- src/java/org/broadinstitute/dropseqrna/utils/editdistance/CollapseTagWithContext.java
- src/java/org/broadinstitute/dropseqrna/utils/readiterators/MapQualityFilteredIterator.java
- src/java/org/broadinstitute/dropseqrna/utils/readiterators/MapQualityPredicate.java
- src/java/org/broadinstitute/dropseqrna/utils/readiterators/RequiredTagPredicate.java
@alecw Some additional refactoring here.  I think it's a bit more clean now, and the fast/slow iteration methods have less unique code per path.
> Aw ctwc ideas

- src/java/org/broadinstitute/dropseqrna/readtrimming/PolyATrimmer.java
- src/java/org/broadinstitute/dropseqrna/utils/FilterBam.java
- src/java/org/broadinstitute/dropseqrna/utils/FilterBamByTag.java
- src/java/org/broadinstitute/dropseqrna/utils/TagBamWithReadSequenceExtended.java
...so it is cleared how many reads went in and out of the program.
> Print terminal message in various Bam processors

- src/java/org/broadinstitute/dropseqrna/utils/FilterBam.java
- src/java/org/broadinstitute/dropseqrna/utils/FilterBamByTag.java
- src/java/org/broadinstitute/dropseqrna/utils/FilterProgramUtils.java
- src/tests/java/org/broadinstitute/dropseqrna/utils/FilterBamByTagTest.java
- src/tests/java/org/broadinstitute/dropseqrna/utils/FilterBamTest.java
> Give Filter* programs the ability to fail if not enough reads, or a too-small portion of reads

- src/java/org/broadinstitute/dropseqrna/annotation/GatherGeneGCLength.java
- src/java/org/broadinstitute/dropseqrna/utils/FastaSequenceFileWriter.java
- src/scripts/public_clp_template.sh
Also, make public_clp_template.sh work even when Picard CLP option convetions change.
> Use FastaReferenceWriter for writing fasta files.

- src/java/org/broadinstitute/dropseqrna/barnyard/digitalexpression/tools/DGEMatrix.java
- src/tests/java/org/broadinstitute/dropseqrna/barnyard/digitalexpression/tools/DGEMatrixTest.java
> DGE Matrix removing cell barcodes bugged.

- src/java/org/broadinstitute/dropseqrna/barnyard/digitalexpression/UMICollection.java
- src/tests/java/org/broadinstitute/dropseqrna/barnyard/digitalexpression/UMICollectionTest.java
Tested build and built successfully
> Added ability to downsample transcripts at UMICollection level.

- src/tests/java/org/broadinstitute/dropseqrna/utils/FilterBamTest.java
- src/tests/java/org/broadinstitute/dropseqrna/utils/TestUtils.java
Hi @jamesnemesh ,
Can you confirm that this fixes the problem for you?  And let me know if you think this is lame or OK.  I don't think I want to spend the time to really understand this.
Thanks, Alec
> Hack around OS X problem with Intel Deflater, by disabling on Mac.

- src/java/org/broadinstitute/dropseqrna/annotation/EnhanceGTFRecords.java
- src/tests/java/org/broadinstitute/dropseqrna/annotation/EnhanceGTFRecordsTest.java
- testdata/org/broadinstitute/transcriptome/annotation/gtf_no_exon.gtf
Added code + unit test + unit test data
> Added check for 0 exons, throws exception and reports problem gene name.

- src/java/org/broadinstitute/dropseqrna/utils/FilterBamByTag.java
- src/tests/java/org/broadinstitute/dropseqrna/utils/FilterBamByTagTest.java
> FilterBamByTag can now perform partial matches to bam tag values.  Off

- src/java/org/broadinstitute/dropseqrna/utils/readiterators/BAMTagValueFilter.java
- src/java/org/broadinstitute/dropseqrna/utils/readiterators/CellBarcodeFilteringIterator.java
- src/java/org/broadinstitute/dropseqrna/utils/readiterators/ChromosomeFilteringIterator.java
- src/java/org/broadinstitute/dropseqrna/utils/readiterators/ChromosomeFilteringPredicate.java
- src/java/org/broadinstitute/dropseqrna/utils/readiterators/EditDistanceFilteringIterator.java
- src/java/org/broadinstitute/dropseqrna/utils/readiterators/ReadEditDistancePredicate.java
- src/java/org/broadinstitute/dropseqrna/utils/readiterators/RequiredTagStringValuePredicate.java
- src/tests/java/org/broadinstitute/dropseqrna/utils/readiterators/ChromosomeFilteringIteratorTest.java
- src/tests/java/org/broadinstitute/dropseqrna/utils/readiterators/EditDistanceFilteringIteratorTest.java
Refactored a number of filtering iterators - new Predicate classes generated, filtering iterators use these predicates via composition.
> Refactoring Filtering iterators to have predicates.

- src/java/org/broadinstitute/dropseqrna/vcftools/CreateSnpIntervalFromVcf.java
Sets GQ_THRESHOLD to -1, which is the value the VCF parser returns when
GQ is not available.
> Fix when there's no GenotypeQuality in the VCF header.

- src/java/org/broadinstitute/dropseqrna/barnyard/digitalallelecounts/SummarizeUMIBaseQualities.java
Very rare edge case where a UMI is observed with exactly 2 reads
with two different bases.  They disagree, so the "most common" base is
randomly one of the two.  This could cause the collection of bases to
have an average error rate close to 1, and Phred encoding would round it
to 0.  This would then cause some likelihood scores to be log (0), which
is bad m'kay?
> Fix for an edge case where reads disagree for a UMI

- src/java/org/broadinstitute/dropseqrna/utils/SplitBamByCell.java
- src/tests/java/org/broadinstitute/dropseqrna/utils/SplitBamByCellTest.java
If any of the options OUTPUT, OUTPUT_LIST or REPORT are not specified set a default value for that option
> Allow the OUTPUT option to be null

- src/java/org/broadinstitute/dropseqrna/utils/SplitBamByCell.java
Changed the default for DELETE_INPUTS to true
> Added short names for some of the options

- src/java/org/broadinstitute/dropseqrna/barnyard/digitalallelecounts/SNPUMIBasePileupIterator.java
Added a SAM read sink to emit informative reads.
> Update to Iterator

- src/java/org/broadinstitute/dropseqrna/barnyard/digitalallelecounts/DigitalAlleleCountsBestGeneIterator.java
- src/java/org/broadinstitute/dropseqrna/barnyard/digitalallelecounts/LikelihoodUtils.java
- src/java/org/broadinstitute/dropseqrna/barnyard/digitalallelecounts/SNPBasePileUp.java
- src/java/org/broadinstitute/dropseqrna/barnyard/digitalallelecounts/SNPIntervalRecordI.java
- src/java/org/broadinstitute/dropseqrna/censusseq/CensusSeq.java
- src/java/org/broadinstitute/dropseqrna/censusseq/CsiAnalysis.java
- src/java/org/broadinstitute/dropseqrna/censusseq/RollCall.java
- src/java/org/broadinstitute/dropseqrna/censusseq/VCFPileupJointIterator.java
- src/tests/java/org/broadinstitute/dropseqrna/barnyard/digitalallelecounts/LikelihoodUtilsTest.java
Finally!  Updates will affect APIs in private.
> Jn donor likelihood

- src/tests/java/org/broadinstitute/dropseqrna/censusseq/CensusSeqTest.java
- src/tests/java/org/broadinstitute/dropseqrna/censusseq/CsiAnalysisTest.java
Tests now expect the exception being throw.
> Fixed tests where the wrong sample list is submitted

- src/java/org/broadinstitute/dropseqrna/utils/readiterators/GeneFunctionIteratorWrapper.java
GeneFunctionIteratorWrapper expose useful function.
> Made getLocusFunction static and public for reuse.

- src/java/org/broadinstitute/dropseqrna/readtrimming/FixedMismatchStartingSequenceTrimmer.java
- src/java/org/broadinstitute/dropseqrna/readtrimming/MismatchRateStartingSequenceTrimmer.java
- src/java/org/broadinstitute/dropseqrna/readtrimming/StartingSequenceTrimmer.java
- src/java/org/broadinstitute/dropseqrna/readtrimming/TrimStartingSequence.java
- src/tests/java/org/broadinstitute/dropseqrna/readtrimming/TrimStartingSequenceTest.java
> New algorithm with mismatch rate and sequence not require to

- src/java/org/broadinstitute/dropseqrna/spermseq/metrics/duplicates/SpermSeqMarkDuplicates.java
Added custom command line validation to cleanup I/O.
SpermSeqMarkDuplicates now accepts wildcard inputs or a file containing a list of file paths.
> SpermSeqMarkDupes input now accepts lists of BAMs, wildcards, etc

- src/java/org/broadinstitute/dropseqrna/barnyard/digitalallelecounts/sampleassignment/multisample/DetectDoublets.java
When a cell has 0 informative UMIs, the best pair for the cell is null.
When this occurs, use the "stock" missing data object instead so file
writing doesn't fail, and write a warning to the user about that cell
barcode being problematic.
> Correction for doublet detection:

- src/java/org/broadinstitute/dropseqrna/barnyard/digitalallelecounts/SNPInfoCollection.java
- src/java/org/broadinstitute/dropseqrna/barnyard/digitalallelecounts/sampleassignment/SampleGenotypeProbabilitiesIterator.java
> Some notes to prepare for dropulation read doublecount fix.

- src/tests/java/org/broadinstitute/dropseqrna/utils/FilteredReadsMetricTest.java
- testdata/org/broadinstitute/dropseq/utils/13.organism_filter_metrics
- testdata/org/broadinstitute/dropseq/utils/14.organism_filter_metrics
> Added some tests to make sure merging works properly after adding

- src/java/org/broadinstitute/dropseqrna/metrics/BamTagHistogram.java
- src/java/org/broadinstitute/dropseqrna/utils/DownsampleBamByTag.java
- src/tests/java/org/broadinstitute/dropseqrna/metrics/BamTagHistogramTest.java
- src/tests/java/org/broadinstitute/dropseqrna/utils/ConvertTagToReadGroupTest.java
- src/tests/java/org/broadinstitute/dropseqrna/utils/DownsampleBamByTagTest.java
Updating a few programs to support multiple BAM files to simplify some analysis.
> BamTagHistogram and DownsampleBamByTag now support multiple input files

- src/ant/defs.xml
Updating release version to 2.5.4 ahead of tagging and release notes
> update public version

- src/java/org/broadinstitute/dropseqrna/barnyard/digitalexpression/AbstractTripletDgeWriterClp.java
- src/java/org/broadinstitute/dropseqrna/cluster/MergeDgeSparse.java
- src/tests/java/org/broadinstitute/dropseqrna/cluster/MergeDgeSparseTest.java
- barcodes.tsv(.gz)
- genes.tsv(.gz)
- features.tsv(.gz)
> Add ability to write names files

- src/java/org/broadinstitute/dropseqrna/annotation/FunctionalData.java
- src/java/org/broadinstitute/dropseqrna/annotation/FunctionalDataProcessor.java
- src/java/org/broadinstitute/dropseqrna/barnyard/DGECommandLineBase.java
- src/java/org/broadinstitute/dropseqrna/utils/readiterators/GeneFunctionIteratorWrapper.java
- src/java/org/broadinstitute/dropseqrna/utils/readiterators/GeneFunctionProcessor.java
- src/java/org/broadinstitute/dropseqrna/utils/readiterators/UMIIterator.java
Digital Expression now works for reads that are not uniquely mapped, following STARsolo's methodology.
> Jn dge multimapper capture

- src/scripts/defs.sh
Trivial fix for #403.
---
~Note:~
* ~This includes commit 4963503ae1219e526a8655c3dc1eaecddb1e3510 and thus all changes suggested in #401.  
Therefore, merging this PR first automatically closes #401.  
See commit cc90ab1c7e39cb9b7026355d3c4b4e6d0a557451 for the additional change suggested here or merge #401 first before reviewing this PR.~
> Handle symlinks

- src/java/org/broadinstitute/dropseqrna/utils/IteratorOfIterators.java
Also closes internal iterators when moving to the next iterator.
> Utility function for creating an IteratorOfIterators passing a mapping function

- src/build/make_wrapper_scripts.sh
- src/build/public_clp_template.sh
- src/scripts/Drop-seq_alignment.sh
- src/scripts/create_Drop-seq_reference_metadata.sh
- src/scripts/defs.sh
This PR bundles a bunch of cleanups and minor fixes of the shell scripts.
I tried to keep the commits small and commit messages informative to ease the review process.
This does not add any functionality or improve the performance but rather enforces a consistent style (I tried to stick to what was mostly used) and simplify the code as much as possible.
If this gets merged, I plan to submit one more PR that builds on top of this cleaned up code that should enable significant speed-ups and (temporary) disk space savings.
Please feel free to suggest any improvements/changes or ask for the reasoning behind particular changes, if required.
> Shell script cleanup

- src/R/packages/DropSeq.dropulation/DESCRIPTION
- src/R/packages/DropSeq.utilities/DESCRIPTION
A new day, a new version of R oxygen
> Update ROxygen version

- src/testFixtures/java/org/broadinstitute/dropseqrna/utils/TestUtils.java
- testdata/org/broadinstitute/dropseq/barnyard/6T.chimeric_read_metrics
Fix one expected test file that I think was wrong.
> testFilesSame was not failing if last non-empty line in file differed.

- src/java/org/broadinstitute/dropseqrna/utils/AbstractSplitBamClp.java
> Early validation that outputs are writable
